# To add an additional team, simply add a top-level key with a list of users.
# NOTE - this should be kept in sync with the GX org's teams

devrel:
  - "@klavavej" # Kristen Lavavej
  - "@r34ctor" # Nevin Tan

core:
  - "@NathanFarmer" # Nathan Farmer
  - "@alena-hutchinson" # Alena Hutchinson
  - "@annabarr" # Anna Barr
  - "@ashmortar" # Aaron Ross
  - "@billdirks" # Bill Dirks
  - "@dctalbot" # David Talbot
  - "@donaldheppner" # Don Heppner
  - "@gyermich" # Galina Yermicheva
  - "@josectobar" # José Tobar
  - "@joshua-stauffer" # Josh Stauffer
  - "@nicgrayson" # Nic Grayson
  - "@shiplet" # Michael Shiplet
  - "@sujensen" # Susan Jensen
  - "@tyler-hoffman" # Tyler Hoffman
  - "@wookasz" # Łukasz Lempart

bot:
  - "@dependabot"
  - "@dependabot[bot]"
  - "@pre-commit-ci[bot]"
