events {}

http {
    upstream mercury-service-api-v1 {
        server mercury-service-api-v1:6002;
    }


    server {
        listen 5000;

        location /api {
            proxy_pass http://mercury-service-api-v1;
        }
    }
}
