---
# Reference: https://github.com/actions/stale#all-options

name: StaleBot

on:
  schedule:
    - cron: "0 0 * * *" # Runs at midnight UTC every day

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      pull-requests: write
    steps:
      - uses: actions/stale@v10
        with:
          # General
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          operations-per-run: 1000
          days-before-stale: 30
          days-before-close: 60

          # exempt all issues
          days-before-issue-stale: -1
          days-before-issue-close: -1

          # Issue messages
          stale-issue-message: >
            Is this issue still relevant? If so, what is blocking it? Is there anything you can do to help move it forward?


            This issue has been automatically marked as stale because it has not had recent activity.


            It will be closed if no further activity occurs. Thank you for your contributions 🙇

          close-issue-message: >
            We are closing this issue due to inactivity.


            This action is done automatically by StaleBot.


            Please validate this is still an issue, and create a new issue with up-to-date information if any problem presists 🙂


            Please reach out if you need anything further. 🙂

          # PR Messages
          stale-pr-message: >
            Is this PR still relevant? If so, what is blocking it? Is there anything you can do to help move it forward?


            This issue has been automatically marked as stale because it has not had recent activity.


            It will be closed if no further activity occurs. Thank you for your contributions 🙇

          close-pr-message: >
            We are closing this PR due to inacitvity.


            This action is done automatically by StaleBot.


            Please reach out if you need anything further. 🙂
